Change logging severity from error -> trace
While running QuickCheck tests, I would occasionally see these errors logged:

    14:10:34.298 ERROR [ForkJoinPool-1-worker-3] o.c.i.BatchWriter - Write Exception {}
     java.util.concurrent.ExecutionException: org.corfudb.runtime.exceptions.OverwriteException
            at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
    Caused by: org.corfudb.runtime.exceptions.OverwriteException: null
            at org.corfudb.infrastructure.BatchWriter.batchWriteProcessor(BatchWriter.java:92)

QC was able to shrink an offending case down to a simple race between
two threads, e.g. put("a", "val") vs. containsKey("a").  Perhaps 10%
of the time, the above error will be generated.

On closer examination, this is not an exceptional condition.  When
scheduler interleaving creates conditions where a client triggers a
hole fill, then the above message is a side-effect.  However, the
results of both the put() and containsKey() are correct, and the
client doesn't appear to do extra work (e.g., retry loop, sleep, etc.)
that isn't already required by the hole fill process.