Backport fixes from corfu-0.4.2.4 to corfu-0.4.2.3 (#4080)
* Check file modification in FileWatcher before invoking callbacks (#4054)

Java NIO WatchService might fire events upon metadata changes on certain
platforms, e.g. Linux inotify IN_ATTRIB. This could cause unnecessary cert
hot-swapping workflows in both Corfu server and client, and cause connection
interruptions.

This PR reduces unnecessary connection restarts by checking the last modified
time of the watched files.

(cherry picked from commit 42989a02eab9138e24708f76c27e1f290972e43a)

* Disable RoaringBitMap cardinality cache in StreamAddressSpace no-arg constructor (#4059)

It is intended that cardinality cache of RoaringBitmap should be disabled by
default in order to avoid non-theadsafe bitmap anomalies. This PR fixes the
no-arg constructor of StreamAddressSpace to disable the cache.

(cherry picked from commit 6ade98a7889cef236d2007bae46edf1b0a301880)

* Use eclipse-temurin:11-jdk-noble (#4071)

Reason:
ERROR: failed to build: failed to solve: openjdk:17-jdk-bullseye: docker.io/library/openjdk:17-jdk-bullseye: not found
ERROR: failed to build: failed to solve: openjdk:11-jdk-bullseye: docker.io/library/openjdk:11-jdk-bullseye: not found

(cherry picked from commit 949705ee2485b5bd9c2d8909023d0124af2e91db)

---------

Co-authored-by: Chetan Gudisagar <chetangudisagar@gmail.com>