Use eclipse-temurin:11-jdk-noble (#4071)
Reason:
ERROR: failed to build: failed to solve: openjdk:17-jdk-bullseye: docker.io/library/openjdk:17-jdk-bullseye: not found
ERROR: failed to build: failed to solve: openjdk:11-jdk-bullseye: docker.io/library/openjdk:11-jdk-bullseye: not found

(cherry picked from commit 949705ee2485b5bd9c2d8909023d0124af2e91db)