Fix class path / JAR file creation anomaly wrt QuickCheck glue
I don't understand Maven enough to understand what the <scope>
and <type> items here do, but their presence in the description
of the `findbugs-maven-plugin` dependency cause Apache Maven 3.3.9
to not include `org/codehaus/plexus/util/ExceptionUtils`, which
AFAIK has a different dependency path entirely ... weird.

     10:03:57.228 DEBUG [org.corfudb.runtime.clients.NettyClientRouter$2event-0] o.c.r.c.NettyClientRouter - Remove request 0 due to timeout!
     Exception in thread "DistErl-0" java.lang.NoClassDefFoundError: org/codehaus/plexus/util/ExceptionUtils
    	at org.corfudb.cmdlets.corfu_layout.main(corfu_layout.java:146)
    	at org.corfudb.cmdlets.CmdletRouter.main2(CmdletRouter.java:52)
    	at org.corfudb.cmdlets.QuickCheckMode.runErlMbox(QuickCheckMode.java:123)
    	at org.corfudb.cmdlets.QuickCheckMode.runErlMbox0(QuickCheckMode.java:75)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.util.ExceptionUtils
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    	... 5 more